### ISSUE TITLE
Intermittent db timeouts

### ISSUE THREAD

**Issue by cavis** [PRX/castle.prx.org#79]
Seeing some 500 errors, usually on podcast/downloads for a large timeframe.  Should figure out if this is postgres being slow, or just running out of db pool connections.  And it seems there's something wrong in the Phoenix error handling too.

```
14:32:48.805 [error] Postgrex.Protocol (#PID<0.346.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.5213.2> timed out because it checked out the connection for longer than 15000ms
14:32:48.805 request_id=j0anb3j4a3p05abdh6ka5fapg2dhinl7 [warn] Could not render errors due to no supported media type in accept header.
Expected one of ["html", "json"] but got the following formats:
* "application/hal+json" with extensions: ["hal"]
To accept custom formats, register them under the `:mime` library
in your config/config.exs file:
config :mime, :types, %{
"application/xml" => ["xml"]
}
And then run `mix deps.clean --build mime` to force it to be recompiled.
. Errors will be rendered using the first accepted format "html" as fallback. Please customize the :accepts option under the :render_errors configuration in your endpoint if you want to support other formats or choose another fallback
14:32:48.805 request_id=j0anb3j4a3p05abdh6ka5fapg2dhinl7 [info] Sent 500 in 15012ms
14:32:48.806 [error] #PID<0.5213.2> running CastleWeb.Endpoint terminated
Server: castle.prx.tech:80 (http)
Request: GET /api/v1/podcasts/151/downloads?interval=1M&from=2018-01-01T00%3A00%3A00.000Z&to=2018-06-25T23%3A59%3A59.999Z
** (exit) an exception was raised:
** (DBConnection.ConnectionError) tcp recv: closed
(ecto) lib/ecto/adapters/postgres/connection.ex:108: Ecto.Adapters.Postgres.Connection.execute/4
(ecto) lib/ecto/adapters/sql.ex:256: Ecto.Adapters.SQL.sql_call/6
(ecto) lib/ecto/adapters/sql.ex:436: Ecto.Adapters.SQL.execute_or_reset/7
(ecto) lib/ecto/repo/queryable.ex:133: Ecto.Repo.Queryable.execute/5
(ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4
(castle) lib/rollup/query/downloads.ex:8: Castle.Rollup.Query.Downloads.podcast/4
(castle) lib/castle_web/controllers/api/download_controller.ex:12: CastleWeb.API.DownloadController.index/2
(castle) lib/castle_web/controllers/api/download_controller.ex:1: CastleWeb.API.DownloadController.action/2
```

**Comment by cavis** [comment]
(still working on this ... tracking down feeder issues)

**Comment by cavis** [comment]
Deploy'd!
