### ISSUE TITLE
406 error when getting request with accept: application/hal+json

### ISSUE THREAD

**Issue by gcampo88** [PRX/castle.prx.org#9]
I get a 406 on publish.prx.dev when attempting to view the download metrics for an episode (hard-coded a guid that did have download data). Here's the error: 
```
# Phoenix.NotAcceptableError at GET /api/v1
Exception:
    ** (Phoenix.NotAcceptableError) no supported media type in accept header, expected one of ["json", "hal"]
        (phoenix) lib/phoenix/controller.ex:965: Phoenix.Controller.refuse/2
        (castle) web/router.ex:12: Castle.Router.api/2
        (castle) web/router.ex:1: Castle.Router.match_route/4
        (castle) web/router.ex:1: Castle.Router.do_call/2
        (castle) lib/castle/endpoint.ex:1: Castle.Endpoint.phoenix_pipeline/1
        (castle) lib/plug/debugger.ex:123: Castle.Endpoint."call (overridable 3)"/2
        (castle) lib/castle/endpoint.ex:1: Castle.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /Users/gigiblum-campo/Desktop/castle.prx.org/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

When I changed the headers of the request to accept application/json instead of application/hal+json, the request worked. (line I changed: https://github.com/PRX/publish.prx.org/blob/master/src/app/core/cms/halremote.ts#L104)

Not sure if this belongs here or in publish!

**Comment by cavis** [comment]
Is this still an issue?  I'm not sure what the problem/resolution was here.

**Comment by gcampo88** [comment]
Not able to recreate it now. Closing!
